version: '3'

services:
  db:
    image: postgres:14.3
    container_name: s2credit-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:${DATABASE_PORT}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - s2credit-network

  api:
    build: backend
    container_name: s2credit-api
    restart: always
    ports:
      - 4000:4000
    environment:
      DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@s2credit-db:${DATABASE_PORT}/${DATABASE_NAME}
    depends_on:
      - db
    networks:
      - s2credit-network

  frontend:
    build: frontend
    container_name: s2credit-frontend
    restart: always
    environment:
      API_URL: https://jsonplaceholder.typicode.com
      BACKEND_URL: http://s2credit-api
    ports:
      - 5173:5173
    depends_on:
      - api
    networks:
      - s2credit-network

networks:
  s2credit-network:
    driver: bridge
